blog_user_login:
    path:     /user/login/
    defaults: { _controller: BlogUserBundle:Default:login }
blog_user_creation:
    path:     /user/new/
    defaults: { _controller: BlogUserBundle:Default:new }
blog_user_availability_ajax:
    path:     /user/ajax/{username}
    defaults: { _controller: BlogUserBundle:Default:ajax }