blog_user_login:
    path:     /user/login/
    defaults: { _controller: BlogUserBundle:Default:login }
blog_user_creation:
    path:     /user/new/
    defaults: { _controller: BlogUserBundle:Default:new }