parameters:
#    blog_user.example.class: Blog\UserBundle\Example

services:
#    blog_user.example:
#        class: %blog_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
